# ALMACENAMIENTO DE DATOS
ARQUITECTURA DE UN DATA WAREHOUSE. CARGA Y MANTENIMIENTO. CUBOS DE DATOS

1. Imporatamos la data

In [1]:
### pip install ucimlrepo

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
car_evaluation = fetch_ucirepo(id=19) 
  
# data (as pandas dataframes) 
X = car_evaluation.data.features 
y = car_evaluation.data.targets 
  
# metadata 
# print(car_evaluation.metadata) 
  
# variable information 
# print(car_evaluation.variables)

In [49]:
# print(car_evaluation)

In [4]:
import pandas as pd

In [5]:
# Combinar X e y en un solo DataFrame para guardarlo en Excel
combined_data = pd.concat([X, y], axis=1)

# Guardar el DataFrame en un archivo Excel
combined_data.to_excel("car_evaluation_data.xlsx", index=False)

print("Los datos se han guardado en car_evaluation_data.xlsx")

Los datos se han guardado en car_evaluation_data.xlsx

In [48]:
# print(combined_data)

4. Extraer nombres de los atributos

In [7]:
list(car_evaluation)

['data', 'metadata', 'variables']

In [8]:
list(combined_data)

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [9]:
import pandas as pd

In [10]:
list(combined_data.columns)

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [11]:
combined_data.columns.tolist()

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [12]:
list(combined_data.columns.values)

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

5. Para medir el rendimiento de los métodos anteriores en términos de tiempo podemos usar la función ‘timeit’ de la librería ‘timeit’.

In [13]:
from timeit import timeit

In [14]:
t1 = timeit(lambda: list(combined_data))
print(t1)

3.3687549000023864

In [15]:
t2 = timeit(lambda: list(combined_data.columns))
print(t2)

1.9338889999999083

In [16]:
t3 = timeit(lambda: combined_data.columns.tolist())
print(t3)

0.43349559999842313

In [17]:
t4 = timeit(lambda: list(combined_data.columns.values))
print(t4)

2.4428168999984337

In [18]:
print(t1,t2,t3,t4)

3.3687549000023864 1.9338889999999083 0.43349559999842313 2.4428168999984337

6.	Usando el método ‘dtype’ para cada atributo, podemos ver su naturaleza. Si quisiéramos ver esto para todos los atributos, usaremos el método ‘dtypes’.

In [19]:
combined_data['buying'].dtype

dtype('O')

In [20]:
combined_data['persons'].dtype

dtype('O')

In [21]:
combined_data.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
class       object
dtype: object

7.	Observamos la cantidad de categorías de un atributo mediante el método ‘unique( )’.

In [22]:
combined_data["doors"].unique

<bound method Series.unique of 0           2
1           2
2           2
3           2
4           2
        ...
1723    5more
1724    5more
1725    5more
1726    5more
1727    5more
Name: doors, Length: 1728, dtype: object>

8.	Si en el paso anterior, la naturaleza de los atributos no coincide en cómo se está definiendo en el repositorio web, podemos cambiar esto por medio del método ‘astype( )’ aplicado sobre el atributo junto con su tipo.

In [23]:
# cambiando tipo de los datos
combined_data['doors'] = combined_data['doors'].astype('category')
combined_data['persons'] = combined_data['persons'].astype('category')

In [24]:
combined_data.astype

<bound method NDFrame.astype of      buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]>

9.	Para cambiar el nombre a las categorías debemos importar la librería ‘numpy’ que trabaja con arreglos y luego utilizar el método ‘where( )’ indicando al atributo de la data, el nuevo nombre para cada categoría.

In [25]:
import numpy as np

In [26]:
combined_data["lug_boot"]=np.where(combined_data["lug_boot"]=="small", "pequeño", combined_data["lug_boot"])
combined_data["lug_boot"]=np.where(combined_data["lug_boot"]=="med", "mediano", combined_data["lug_boot"])
combined_data["lug_boot"]=np.where(combined_data["lug_boot"]=="big", "grande", combined_data["lug_boot"])
combined_data["lug_boot"].unique

<bound method Series.unique of 0       pequeño
1       pequeño
2       pequeño
3       mediano
4       mediano
         ...
1723    mediano
1724    mediano
1725     grande
1726     grande
1727     grande
Name: lug_boot, Length: 1728, dtype: object>

10.	Con el método ‘.value_count( )’ podemos contabilizar las frecuencias de cada categoría.

In [27]:
combined_data["doors"].value_counts(dropna=False)

doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64

11.	También podemos juntar dos o más categorías mediante el método ‘where’ escribiendo la misma categoría para las que son diferentes.

In [28]:
combined_data["doors"] = np.where(combined_data["doors"]=="2", "3 a menos", combined_data["doors"])
combined_data["doors"] = np.where(combined_data["doors"]=="3", "3 a menos", combined_data["doors"])

In [29]:
combined_data["doors"] = np.where(combined_data["doors"]=="4", "4 a más", combined_data["doors"])
combined_data["doors"] = np.where(combined_data["doors"]=="5more", "4 a más", combined_data["doors"])

In [30]:
combined_data["doors"].unique()

array(['3 a menos', '4 a más'], dtype=object)

12.	Otra forma de cambiar los nombres de los encabezados es mediante el método ‘rename’ escribiendo en forma de diccionario, el nombre de la variable a cambiar (‘lug_boot’) y luego el nuevo nombre (‘trunk’). Además, debemos asignar el valor ‘axis=1’ y si queremos cambiar nombres a las filas usamos ‘axis=0’.

In [31]:
combined_data.rename({'lug_boot':'trunk'}, axis=1, inplace=True)
combined_data

     buying  maint      doors persons    trunk safety  class
0     vhigh  vhigh  3 a menos       2  pequeño    low  unacc
1     vhigh  vhigh  3 a menos       2  pequeño    med  unacc
2     vhigh  vhigh  3 a menos       2  pequeño   high  unacc
3     vhigh  vhigh  3 a menos       2  mediano    low  unacc
4     vhigh  vhigh  3 a menos       2  mediano    med  unacc
...     ...    ...        ...     ...      ...    ...    ...
1723    low    low    4 a más    more  mediano    med   good
1724    low    low    4 a más    more  mediano   high  vgood
1725    low    low    4 a más    more   grande    low  unacc
1726    low    low    4 a más    more   grande    med   good
1727    low    low    4 a más    more   grande   high  vgood

[1728 rows x 7 columns]

13.	Para determinar la cantidad de registros y atributos utilizamos el método ‘shape( )’; asimismo, con los métodos ‘head( )’ y ‘tail( )’, podemos ver los 5 primeros y últimos registros, respectivamente.

In [32]:
# n de registros y atributos
combined_data.shape

(1728, 7)

In [33]:
combined_data.head()

  buying  maint      doors persons    trunk safety  class
0  vhigh  vhigh  3 a menos       2  pequeño    low  unacc
1  vhigh  vhigh  3 a menos       2  pequeño    med  unacc
2  vhigh  vhigh  3 a menos       2  pequeño   high  unacc
3  vhigh  vhigh  3 a menos       2  mediano    low  unacc
4  vhigh  vhigh  3 a menos       2  mediano    med  unacc

In [34]:
combined_data.tail()

     buying maint    doors persons    trunk safety  class
1723    low   low  4 a más    more  mediano    med   good
1724    low   low  4 a más    more  mediano   high  vgood
1725    low   low  4 a más    more   grande    low  unacc
1726    low   low  4 a más    more   grande    med   good
1727    low   low  4 a más    more   grande   high  vgood

14.	Con el método ‘iloc’ podemos extraer una parte de nuestra data a manera de filas y columnas.

In [35]:
combined_data.iloc[0:3, 1:4]

   maint      doors persons
0  vhigh  3 a menos       2
1  vhigh  3 a menos       2
2  vhigh  3 a menos       2

15.	Para extraer registros en particular, podemos hacer uso de los corchetes ([ ]) especificando dentro de estos los registros que necesitamos.

In [36]:
combined_data.loc[[0,10],:]

   buying  maint      doors persons    trunk safety  class
0   vhigh  vhigh  3 a menos       2  pequeño    low  unacc
10  vhigh  vhigh  3 a menos       4  pequeño    med  unacc

16.	Con relación a lo anterior, también se pueden utilizar los corchetes para extraer los datos de un atributo o más de uno, colocando para ello sus nombres.

In [37]:
combined_data.loc[0:20,['doors', 'persons']]

        doors persons
0   3 a menos       2
1   3 a menos       2
2   3 a menos       2
3   3 a menos       2
4   3 a menos       2
5   3 a menos       2
6   3 a menos       2
7   3 a menos       2
8   3 a menos       2
9   3 a menos       4
10  3 a menos       4
11  3 a menos       4
12  3 a menos       4
13  3 a menos       4
14  3 a menos       4
15  3 a menos       4
16  3 a menos       4
17  3 a menos       4
18  3 a menos    more
19  3 a menos    more
20  3 a menos    more

17.	También se pueden utilizar los corchetes para extraer los datos de una categoría en particular de un atributo.

In [38]:
combined_data[combined_data.buying=='vhigh']

    buying  maint      doors persons    trunk safety  class
0    vhigh  vhigh  3 a menos       2  pequeño    low  unacc
1    vhigh  vhigh  3 a menos       2  pequeño    med  unacc
2    vhigh  vhigh  3 a menos       2  pequeño   high  unacc
3    vhigh  vhigh  3 a menos       2  mediano    low  unacc
4    vhigh  vhigh  3 a menos       2  mediano    med  unacc
..     ...    ...        ...     ...      ...    ...    ...
427  vhigh    low    4 a más    more  mediano    med    acc
428  vhigh    low    4 a más    more  mediano   high    acc
429  vhigh    low    4 a más    more   grande    low  unacc
430  vhigh    low    4 a más    more   grande    med    acc
431  vhigh    low    4 a más    more   grande   high    acc

[432 rows x 7 columns]

18.	Utilizando operadores lógicos, se pueden combinar condiciones y aplicar lo anterior.

In [39]:
combined_data[(combined_data.safety=='med') | (combined_data.safety=='high')]

     buying  maint      doors persons    trunk safety  class
1     vhigh  vhigh  3 a menos       2  pequeño    med  unacc
2     vhigh  vhigh  3 a menos       2  pequeño   high  unacc
4     vhigh  vhigh  3 a menos       2  mediano    med  unacc
5     vhigh  vhigh  3 a menos       2  mediano   high  unacc
7     vhigh  vhigh  3 a menos       2   grande    med  unacc
...     ...    ...        ...     ...      ...    ...    ...
1721    low    low    4 a más    more  pequeño   high   good
1723    low    low    4 a más    more  mediano    med   good
1724    low    low    4 a más    more  mediano   high  vgood
1726    low    low    4 a más    more   grande    med   good
1727    low    low    4 a más    more   grande   high  vgood

[1152 rows x 7 columns]

19.	Por último, si deseamos exportar nuestro documento a un csv adicionándole la ruta donde queremos guardar nuestro documento.

In [40]:
import os
import pyperclip

copiamos el directorio actual

In [41]:
directorio_actual = os.getcwd()
print(directorio_actual)

c:\TECSUP\5-tecsup\Mineria de Datos\Semana (3)\LAB

In [42]:
directorio_esc = directorio_actual.replace("\\", "\\\\")

pyperclip.copy(directorio_esc)

print(f"El directorio escapado '{directorio_esc}' se ha copiado al portapapeles.")

El directorio escapado 'c:\\TECSUP\\5-tecsup\\Mineria de Datos\\Semana (3)\\LAB' se ha copiado al portapapeles.

aplicamos la ruta

In [43]:
ruta='C:\\TECSUP\\5-tecsup\\Mineria de Datos\\Semana (3)\\LAB\\combined_data.csv'

In [44]:
### combined_data.to_csv(ruta)
# invalido porque arroja los datos en mal formato

HACEMOS UNA CORRECIÓN DE FORMATOS CON ucimlrepo

In [45]:
from ucimlrepo import fetch_ucirepo

In [46]:
# fetch dataset
car_evaluation = fetch_ucirepo(id=19)

In [50]:
# Guardar el DataFrame en un archivo CSV con codificación UTF-8
combined_data.to_csv("DATA_FORMATEADA.csv", index=False, encoding="ISO-8859-1")

print("Los datos se han guardado en car_evaluation_data.csv con codificación ISO-8859-1.")

Los datos se han guardado en car_evaluation_data.csv con codificación ISO-8859-1.

20.	A continuación, se muestran los métodos más importantes que existen para importar y exportar datos en Python.

from IPython.display import HTML

tabla_html = """
<table>
  <thead>
    <tr>
      <th>Formato archivo</th>
      <th>Importar (leer)</th>
      <th>Exportar (guardar)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>csv</td>
      <td>pd.read_csv()</td>
      <td>df.to_csv()</td>
    </tr>
    <tr>
      <td>json</td>
      <td>pd.read_json()</td>
      <td>df.to_json()</td>
    </tr>
    <tr>
      <td>excel</td>
      <td>pd.read_excel()</td>
      <td>df.to_excel()</td>
    </tr>
    <tr>
      <td>sql</td>
      <td>pd.read_sql()</td>
      <td>df.to_sql()</td>
    </tr>
  </tbody>
</table>
"""

HTML(tabla_html)